name: Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
      fail-fast: false
    name: Python ${{ matrix.python-version }} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements (Python 3)
        run: pip install -r requirements-dev.txt && pip install .
      - name: Run tests
        run: pytest --cov=ckanserviceprovider --cov-append --cov-report=xml --disable-warnings tests
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
